### ISSUE TITLE
Missing project file

### ISSUE THREAD

**Issue by chcg** [Bassman2/JiraWebApi#1]
See https://github.com/Bassman2/JiraWebApi/blob/10b7ebfc6159802db5a2b61e1574f087d986c5cb/JiraWebApi.sln#L8

this project is missing on github.

**Comment by Bassman2** [comment]
The JiraWebApiTest Project contains private passwords and runs only on my JIRA Servers. 
So I can't commit it and I can't delete it because I need it for my own tests. 
Sorry
